version: '3.4'

services:
  server:
    image: db_project
    container_name: "db_project"
    build: ./Dockerfile.local
    volumes:
      - ./.build/volumes/logs:/logs
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - ./.build/volumes/databases/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432docker-compose.yml
